travis:
  secure:
    BINSTAR_TOKEN: c4nX3jb0YH/V23zbZK4Y8QnyoaJ7Y/sLbrrPD7cihcJGnLELfoBgelVJ+Ov9Sg/YR0NmdgtNOvNLgqEAfQ2jV8OD0+Gs62pyQYW7kdCEWCd7pWj+K6hARoNDZvzmakwAUjOD9rZ+iJuuMRpA0fuqcn+d63rSGG9D9DAG7GAi9vp+p6D8a3D2JbOgDJHB7V8on4wePtGdRP76P9gcLf60jbXkOJTCUJl5aUV1usmuAMdeaR5zAS5GIzKW8Wde0xSvl0OLgOid8lQHoxy9ep4Sxq6g5Q1Eb5fRQFRyJvTH9cITxPo23DiHBGqpZwCgZfuWMx4eFiV9u3UM5byTYOM0Hr37T9OfunGhx+yyKp9YEMHhzzXNtHQY84t3185rnzz/yAo2bsOhObHrgEb0Cpx5cpHdUO2iIVzJp2kLApQbrr+H76oFcOgswZ0Ed0SqQZ7wFSIW88CX0oc55vuGGpGkn1Y27irmE+mBJsuBlubUJtaA6m1MG6e+BDb0hmAeQINwpNbnIjyS3Z+t3SvX/r2sIALWCbm3u+LBJYRMumIf5w6YYbtGxMJsm722pHu9IH/tLvJIU9bxUHAWsjsTzCtqLO7cQaU8ZYQOWbp/f00NYJv/gnhG/3n+iV3mI4S3+XjcdjRHAZAnQLTKS6POBwEsw98FT5KWV2wjRzo5nM9yXW8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
